export const TEMPLATE_CATEGORIES = [
  "All",
  "Ads & Product",
  "Brand & Logo",
  "Videos",
  "Illustration & 3D",
  "Posters & Visuals",
  "Portraits",
  "Wallpaper",
] as const;

export type TemplateCategory = (typeof TEMPLATE_CATEGORIES)[number];
export type TemplateMediaType = "image" | "video";

export type PromptTemplate = {
  id: string;
  source: string;
  sourcePromptId?: string;
  sourceUrl?: string;
  title: string;
  prompt: string;
  thumbnailUrl: string;
  mediaType: TemplateMediaType;
  model: string;
  aspectRatio: string;
  category: TemplateCategory;
  tags: string[];
  authorName?: string;
  published: boolean;
  featured: boolean;
};

export const DEFAULT_PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: "img-product-perfume-golden",
    source: "internal",
    title: "Luxury Perfume Launch",
    prompt: "A luxury perfume bottle on reflective black glass, cinematic golden rim light, premium ad campaign, ultra-detailed product photography, elegant shadows, commercial studio setup, sharp focus, rich amber highlights.",
    thumbnailUrl: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "GPT Image 2",
    aspectRatio: "4:3",
    category: "Ads & Product",
    tags: ["Ads & Product", "Product", "Luxury", "Commercial"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "img-logo-minimal-coffee",
    source: "internal",
    title: "Minimal Coffee Brand Logo",
    prompt: "Minimal premium coffee brand logo exploration, clean monoline symbol, warm earthy palette, modern typography, branding presentation on textured paper, studio lighting, elegant and memorable identity.",
    thumbnailUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "GPT Image 2",
    aspectRatio: "1:1",
    category: "Brand & Logo",
    tags: ["Brand & Logo", "Logo", "Minimal", "Identity"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "img-mecha-city-3d",
    source: "internal",
    title: "Mecha Alley Concept",
    prompt: "Futuristic neon alley with giant mecha mechanic workshop, volumetric fog, cinematic blue and magenta lighting, highly detailed environment concept art, 3D illustration quality, immersive depth.",
    thumbnailUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "Seedream 5 Lite",
    aspectRatio: "16:9",
    category: "Illustration & 3D",
    tags: ["Illustration & 3D", "Sci-Fi", "Environment", "Neon"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "img-poster-cyberpunk-concert",
    source: "internal",
    title: "Cyberpunk Concert Poster",
    prompt: "A bold cyberpunk concert poster, striking typography, holographic lights, energetic crowd silhouettes, high contrast magenta and electric blue palette, premium print design, modern visual hierarchy.",
    thumbnailUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "GPT Image 2",
    aspectRatio: "3:4",
    category: "Posters & Visuals",
    tags: ["Posters & Visuals", "Poster", "Cyberpunk", "Typography"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "img-portrait-editorial-asian",
    source: "internal",
    title: "Editorial Portrait",
    prompt: "Editorial portrait of a stylish young Asian woman in a modern cafe, soft window light, natural skin texture, subtle fashion styling, realistic photography, premium lifestyle magazine look.",
    thumbnailUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "GPT Image 2",
    aspectRatio: "3:4",
    category: "Portraits",
    tags: ["Portraits", "Editorial", "Realistic", "Lifestyle"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "img-wallpaper-aurora-cabin",
    source: "internal",
    title: "Aurora Cabin Wallpaper",
    prompt: "Northern lights over a quiet snowy cabin by a frozen lake, ultra-detailed cinematic landscape, calm atmosphere, rich teal and emerald sky, wallpaper quality, immersive wide composition.",
    thumbnailUrl: "https://images.unsplash.com/photo-1515238152791-8216bfdf89a7?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "Seedream 5 Lite",
    aspectRatio: "16:9",
    category: "Wallpaper",
    tags: ["Wallpaper", "Landscape", "Aurora", "Nature"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "img-product-sneaker-splash",
    source: "internal",
    title: "Sneaker Splash Ad",
    prompt: "Dynamic sneaker advertising shot with water splash frozen in motion, premium studio lighting, dramatic shadows, sports commercial look, crisp material detail, bold campaign composition.",
    thumbnailUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "GPT Image 2",
    aspectRatio: "16:9",
    category: "Ads & Product",
    tags: ["Ads & Product", "Fashion", "Sports", "Commercial"],
    authorName: "Escanor Studio",
    published: true,
    featured: false,
  },
  {
    id: "img-brand-packaging-tea",
    source: "internal",
    title: "Tea Packaging Identity",
    prompt: "Premium tea packaging identity system, soft botanical illustration, modern brand logo, embossed label mockup, elegant color palette, luxury organic product branding presentation.",
    thumbnailUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?auto=format&fit=crop&w=600&q=80",
    mediaType: "image",
    model: "GPT Image 2",
    aspectRatio: "1:1",
    category: "Brand & Logo",
    tags: ["Brand & Logo", "Packaging", "Botanical", "Identity"],
    authorName: "Escanor Studio",
    published: true,
    featured: false,
  },
  {
    id: "vid-product-watch-reveal",
    source: "internal",
    title: "Watch Reveal Teaser",
    prompt: "A luxury wristwatch slowly rotating in a dark studio, macro lighting, sparkling metal reflections, cinematic camera move, premium teaser ad, dramatic pacing, polished commercial look.",
    thumbnailUrl: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=600&q=80",
    mediaType: "video",
    model: "Grok Imagine",
    aspectRatio: "16:9",
    category: "Videos",
    tags: ["Videos", "Ads & Product", "Luxury", "Commercial"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "vid-brand-fashion-bumper",
    source: "internal",
    title: "Fashion Brand Bumper",
    prompt: "A fashion campaign bumper with a confident model walking through wind and soft strobe light, modern editorial styling, dramatic slow motion, premium brand motion piece, clean luxury energy.",
    thumbnailUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
    mediaType: "video",
    model: "Grok Imagine",
    aspectRatio: "9:16",
    category: "Videos",
    tags: ["Videos", "Portraits", "Fashion", "Brand"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "vid-poster-trailer-sci-fi",
    source: "internal",
    title: "Sci-Fi Trailer Shot",
    prompt: "A sci-fi hero standing in a neon rain city, cinematic trailer shot, glowing signage, dramatic dolly-in camera movement, moody atmosphere, premium blockbuster visual language.",
    thumbnailUrl: "https://images.unsplash.com/photo-1520034475321-cbe63696469a?auto=format&fit=crop&w=600&q=80",
    mediaType: "video",
    model: "Grok Imagine",
    aspectRatio: "16:9",
    category: "Videos",
    tags: ["Videos", "Posters & Visuals", "Sci-Fi", "Trailer"],
    authorName: "Escanor Studio",
    published: true,
    featured: true,
  },
  {
    id: "vid-illustration-dragon-flythrough",
    source: "internal",
    title: "Dragon Temple Flythrough",
    prompt: "Fantasy dragon temple flythrough, floating embers, giant statues, mystical light shafts, rich environmental storytelling, high-end cinematic 3D mood, immersive fantasy motion.",
    thumbnailUrl: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=600&q=80",
    mediaType: "video",
    model: "Grok Imagine",
    aspectRatio: "16:9",
    category: "Illustration & 3D",
    tags: ["Illustration & 3D", "Videos", "Fantasy", "Environment"],
    authorName: "Escanor Studio",
    published: true,
    featured: false,
  },
  {
    id: "vid-wallpaper-cloudscape-loop",
    source: "internal",
    title: "Cloudscape Motion Loop",
    prompt: "A dreamy cloudscape at sunset with soft drifting motion, golden light, painterly atmosphere, wide cinematic composition, calming wallpaper-style motion loop.",
    thumbnailUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    mediaType: "video",
    model: "Grok Imagine",
    aspectRatio: "16:9",
    category: "Wallpaper",
    tags: ["Wallpaper", "Videos", "Sky", "Loop"],
    authorName: "Escanor Studio",
    published: true,
    featured: false,
  },
];
